### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/evaluacion-intermedia-modulo-2-anapayanruiz#1]
Really cool job @anapayanruiz  !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Define the logic to make the counter work.
- [x] Use `classList.add('hidden')` to hide invalid clues

### JavaScript: advanced

- [x] Move `ev.preventDefault()` to first line of the function.

### HTML

- [x] Use a `label` to define the content of the input.
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input.
- [x] Use placeholder.
- [x] Inputs must have a type attribute set to a valid value (text, number, mail, button..).

### Steps to finish the game (for those far from the solution)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by anapayanruiz** [comment]
Buenas tardes Miguel, ya he realizado todas las mejoras del proyecto en mi rama improvements. Te envío una pull request para que me lo revises.
Gracias,
